- hosts: all
  vars:
    user: pi
  roles:
  - role: unifi-docker-compose
  tags:
  - docker
  - unifi-docker-compose

- hosts: all
  vars:
    reboot: false
  tasks:

  - name: Unblock WiFI
    command: /usr/sbin/rfkill unblock all

  # See https://docs.python.org/3/library/re.html for further details on syntax
  #  Use backrefs with alternative group syntax to avoid conflicts with variable values
  - name: Update /boot/cmdline.txt to allow cgroups
    become: true
    tags: docker
    ansible.builtin.lineinfile:
      path: /boot/cmdline.txt
      regexp: ^(console=serial0,115200 console=tty1) root=PARTUUID=([0-9a-z-]*) rootfstype=ext4 fsck.repair=yes rootwait
      line: \g<1> root=PARTUUID=\g<2> rootfstype=ext4 fsck.repair=yes rootwait cgroup_memory=1 cgroup_enable=memory
      backrefs: yes

  - name: Update all packages to their latest version
    become: true
    apt:
      name: "*"
      state: latest
      update_cache: yes

  - name: Run the equivalent of "apt-get clean" as a separate step
    become: true
    apt:
      clean: yes

  - name: Reboot the machine with all defaults
    become: true
    reboot:
    when: reboot

- hosts: all
  vars:
    kubeconfig: ~/.kube/config_rpi
  roles:
  - role: k3s

- hosts: all
  roles:
  - role: traefik
