- name: Download k3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s.sh
    mode: '0700'

- name: Install k3s
  shell: K3S_TOKEN=token INSTALL_K3S_CHANNEL=latest K3S_KUBECONFIG_MODE="666" /tmp/k3s.sh server --service-node-port-range "1900-32767"
  args:
    creates: /etc/rancher/k3s/k3s.yaml

- name: Fetch KUBECONFIG to {{ kubeconfig }}
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig }}"
    flat: yes

- name: Amend KUBECONFIG's 127.0.0.1 to rpi IP {{ ansible_host }}
  delegate_to: 127.0.0.1
  lineinfile:
    path: "{{ kubeconfig }}"
    regexp: ^(\s*)server{{ ":" }} https://127.0.0.1:6443
    line: \g<1>server{{ ":" }} https://{{ ansible_host }}:6443
    backrefs: yes
